solettaproject/soletta

src/modules/flow/int/int.c, src/modules/flow/test/int-generator.c, src/test-fbp/irange-buffer.fbp, src/test-fbp/irange-math.fbp
v3 - do not create an error if step == 0, just don't use it.
=> Irange tests v3

data/oic/oicgen.py, src/lib/common/sol-macros.h
=> Silence warnings in OIC generated code.

README.md
New version: https://github.com/lucasdemarchi/soletta/tree/tip/demarchi/readme-v2
=> Add build status to README.md file v2

Makefile.am, configure.ac, src/lib/common/sol-mainloop.c, src/lib/common/sol-pin-mux.c, src/shared/sol-gpio-common.c, src/shared/sol-gpio-linux.c, src/shared/sol-gpio-riot.c, src/shared/sol-i2c-common.c, src/shared/sol-i2c-linux.c, src/shared/sol-i2c-riot.c, src/shared/sol-pwm-common.c, src/shared/sol-pwm-linux.c, src/shared/sol-pwm-riot.c
=> Pin mux v3

src/shared/sol-fbp-parser.c
Signed-off-by: Anselmo L. S. Melo <anselmo.melo@intel.com>
=> fbp-parser: Add missing parenthesis to error msg

src/lib/flow/sol-flow-builder.c, src/lib/flow/sol-flow-builder.h, src/test/test-flow-builder.c
Set type description to use.
v2 changelog:
* start copying all the arguments of sol_flow_builder_set_type_description()
* change symbol and options_symbol handling
=> Builder set type desc v3

src/lib/common/Kconfig, src/lib/common/Makefile, src/lib/common/sol-log.h, src/lib/flow/Kconfig, src/modules/flow/accelerometer/Kconfig, src/modules/flow/gyroscope/Kconfig, src/modules/flow/process/Kconfig, src/shared/Makefile
This series fixes issues raised by @ibriano  and @lucasdemarchi about dependency selection related platform, glib, and so on.
=> random kbuild fixes

src/modules/flow/file/file.c
Since sol_util_strerrora() creates a buffer, there's no need to
create it and use sol_util_strerror().
=> flow: use sol_util_strerrora() instead of sol_util_strerror()

data/oic/oicgen.py, src/bin/sol-fbp-to-dot/main.c, src/lib/comms/sol-oic-client.c, src/lib/comms/sol-oic-server.c, src/lib/flow/sol-flow-parser.c, src/samples/coap/oic-client.c, src/shared/sol-fbp-parser.c, src/test/test-fbp-scanner.c, src/test/test-fbp.c
The macro is there to simplify the operation.
=> Use SOL_STR_SLICE_PRINT()

src/bin/sol-fbp-generator/main.c
now it's possible to pass a directory path to -j and it will search
recursively into the directories for '*.json' files.
=> fbp-generator: start handling directories on JSON arguments

src/bin/sol-fbp-generator/main.c, src/modules/flow/grove/grove.c
They showed up after the addition of new flags on build
=> Fix some general warnings

src/bin/sol-fbp-generator/main.c
-s option now can be used to generate a subflow (without includes
and main)
=> fbp-generator: enable the generation of subflows

src/bin/sol-fbp-generator/main.c, src/bin/sol-fbp-generator/type-store.c, src/lib/flow/sol-flow-builder.c, src/modules/flow/process/common.h, src/modules/flow/process/subprocess.c, src/shared/sol-util-linux.c, src/shared/sol-util.c
Building with musl is a nice feature to generate small static binaries, useful for our linux-micro targets.
More changes are needed, this is the first step with the simple stuff.
=> Part of the fixes required to build with musl-libc

src/modules/flow/float/float.c, src/shared/sol-conffile.c, src/shared/sol-util-linux.c
Just 2 warning messages that I got while compiling to Galileo.
Last patch should fix coverity issue 126309
=> Small fixes

src/shared/sol-conffile.c
=> Conffile: Avoid to leak file_reader structure

src/bin/sol-fbp-runner/runner.c
By adding extra dereference in packet_type is possible to turn
'input_nodes' and 'output_nodes' back to 'static const' structures,
simplifying the initialization and eliminating the need for asserts.
The main reason for this patch was to remove the 'static_assert'
calls because it's not supported by all target platforms (i.e. Galileo).
Signed-off-by: Murilo Belluzzo <murilo.belluzzo@intel.com>
=> Runner: Simplify initialization

src/lib/flow/sol-flow-resolver-conffile.c
Changes from v1:
- Fixed review comments;
Original message:
This is one of the last usages of glib in the core library. Removing
this hash table usage should have little effect, as the number of
entries is the number of different external node types used.
It should be noted that atexit() is still used, and it should have no
adverse effects even if it the callback is called multiple times.
Signed-off-by: Vinicius Costa Gomes <vinicius.gomes@intel.com>
=> flow: Remove GHashTable usage from resolver-conffile

src/modules/flow/string/string-icu.c, src/shared/sol-iio.c
@glima - you may want to review icu fixes.
=> Coverity fixes

src/modules/flow/string/string-ascii.c, src/modules/flow/string/string-icu.c, src/modules/flow/string/string-replace-ascii.c, src/modules/flow/string/string-replace-icu.c, src/modules/flow/string/string.h
And fix coverity issues on this module once and for all (at least
against a local coverity run).
"goto considered harmful"
=> Move ICU helper macros into functions.

src/modules/flow/string/string-ascii.c
=> Fix some string formats for int32_t.

data/jsons/dependencies.json, src/bin/sol-fbp-generator/main.c, src/bin/sol-fbp-generator/type-store.c, src/lib/common/sol-log-impl-linux.c, src/lib/common/sol-missing.h, src/lib/common/sol-platform-impl-linux-micro.c, src/lib/comms/sol-http-client-impl-curl.c, src/lib/comms/sol-network-linux.c, src/lib/comms/sol-oic-client.c, src/lib/datatypes/sol-str-slice.c, src/modules/flow/converter/string-format.c, src/modules/flow/string/string-replace-ascii.c, src/modules/flow/unix-socket/unix-socket-impl.c, src/modules/flow/wallclock/wallclock.c, src/modules/linux-micro/locale/locale.c, src/samples/common/linux-micro-init.c, src/shared/sol-util-file.c, src/shared/sol-util.c, tools/build/Makefile.vars
The following patches enable soletta to be built by musl-1.1.10.
=> Musl fixes

src/lib/common/include/sol-types.h, src/lib/comms/include/sol-http-client.h, src/lib/flow/sol-flow-packet.c, src/modules/flow/byte/byte.c, src/modules/flow/float/float.c, src/modules/flow/flower-power/flower-power.c, src/modules/flow/freegeoip/freegeoip.c, src/modules/flow/int/int.c, src/modules/flow/thingspeak/thingspeak.c
=> Some fixes and improvements required on pr 466

src/modules/flow/string/string-regexp.c
Fixes the follow warning when cross-compiling for galileo:
./src/modules/flow/string/string-regexp.c:213:17: warning: declaration
of 'pcre_extra' shadows a global declaration [-Wshadow]
=> flow:string:regexp: Remove warning

src/lib/common/include/sol-mainloop.h, src/lib/comms/include/sol-coap.h, src/lib/comms/include/sol-http-client.h, src/lib/comms/include/sol-network.h, src/lib/datatypes/include/sol-arena.h, src/lib/datatypes/include/sol-buffer.h, src/lib/datatypes/include/sol-list.h, src/lib/datatypes/include/sol-str-slice.h, src/lib/datatypes/include/sol-str-table.h, src/lib/datatypes/include/sol-vector.h, src/lib/flow/include/sol-flow-simplectype.h, src/lib/io/include/sol-aio.h, src/lib/io/include/sol-gpio.h, src/lib/io/include/sol-i2c.h, src/lib/io/include/sol-pwm.h, src/lib/io/include/sol-spi.h, src/lib/io/include/sol-uart.h, src/shared/sol-iio.h
=> Fix make doc rule errors and add some groups.

src/lib/datatypes/sol-buffer.c
Fixes two issues found with the fuzzer.
=> Buffer fixes

src/bin/sol-fbp-generator/main.c, src/bin/sol-fbp-generator/type-store.c, src/bin/sol-fbp-generator/type-store.h, src/samples/flow/semaphore-monitor/Makefile, src/test-fbp/_exported_options.fbp, src/test-fbp/console-direction-vector.fbp, src/test-fbp/declare_options.fbp, src/test-fbp/filter-repeated.fbp, src/test-fbp/switcher-simple-forward.fbp
Changes since v1:
* Added has_explicit_fields() function.
This replaces #892
=> Sol-fbp-generator: Add support for OPTIONS in FBP declare. v2

src/bin/sol-fbp-runner/main.c, src/lib/common/include/sol-log.h, src/lib/common/include/sol-mainloop.h, src/lib/common/include/sol-platform.h, src/lib/common/include/sol-types.h, src/lib/comms/include/sol-network.h, src/lib/datatypes/include/sol-arena.h, src/lib/datatypes/include/sol-buffer.h, src/lib/datatypes/include/sol-list.h, src/lib/datatypes/include/sol-str-slice.h, src/lib/datatypes/include/sol-str-table.h, src/lib/datatypes/include/sol-vector.h, src/lib/flow/include/sol-flow-inspector.h, src/lib/flow/include/sol-flow-packet.h, src/lib/flow/include/sol-flow-parser.h, src/lib/flow/include/sol-flow-resolver.h, src/lib/flow/include/sol-flow.h, src/lib/io/include/sol-aio.h, src/lib/io/include/sol-gpio.h, src/lib/io/include/sol-i2c.h, src/lib/io/include/sol-iio.h, src/lib/io/include/sol-pwm.h, src/lib/io/include/sol-spi.h, src/lib/io/include/sol-uart.h
Signed-off-by: Murilo Belluzzo <murilo.belluzzo@intel.com>
=> Soletta: because we know our own name

src/lib/comms/sol-http-server-impl-microhttpd.c, src/test-fbp/http-boolean.fbp, src/test-fbp/http-drange.fbp, src/test-fbp/http-irange.fbp, src/test-fbp/http-string.fbp
=> tests: add tests for http server and client and fix double free

src/lib/comms/sol-http-client-impl-curl.c
Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>
=> Fix segfault when request is triggered without setting an url

src/lib/comms/sol-coap.c
packet_extract_path() call, if returned an error, inside
sol_coap_send_packet_with_reply(), could make the latter return an
uninitialized value for 'err'.
=> coap: fix uninitialized variable warning.

src/samples/http/.gitignore, src/samples/http/Kconfig, src/samples/http/Makefile, src/samples/http/server.c, src/samples/http/static-files.c
- from v1
- default port is 8080
- set response's content type
- remove duplicated attribuitation
- deal HUP
- Add sample's description
- Fix read data from stdin
=> HTTP Server samples v2

src/modules/flow/form/form.c
=> flow:form: Fix unintialized variable usage

src/modules/flow/iio/iio.json, src/modules/flow/iio/nodes.c
Change-Id: I882b31d0b58511473561e0496bb9ce8850376dd9
Signed-off-by: guchaojie <chao.jie.gu@intel.com>
=> flow:iio: Add Temperature sensor type support into iio node V3.

src/modules/flow/converter/converter.c, src/modules/flow/converter/string-format.c, src/modules/flow/converter/string-format.h, src/modules/flow/form/form.c
=> form: remove converter dependency

src/samples/http/Makefile
=> build:http: Fix sample dependencies

src/lib/common/include/sol-platform.h, src/lib/common/sol-platform-impl-contiki.c, src/lib/common/sol-platform-impl-linux-micro.c, src/lib/common/sol-platform-impl-riot.c, src/lib/common/sol-platform-impl-systemd.c, src/lib/common/sol-platform-impl.h, src/lib/common/sol-platform-linux-common.c, src/lib/common/sol-platform.c, src/modules/flow/platform/platform.c, src/modules/flow/platform/platform.json, src/samples/flow/misc/Makefile, src/samples/flow/misc/change_locale.fbp
Chances since v3:
* Fixed @ceolin suggstions.
* Removed last commit, since it is not necessary anymore.
=> Platform+Flow: Add locale API and nodes V4

src/lib/comms/include/sol-oic-client.h
=> comms/oic: fix docs

src/lib/common/include/sol-mainloop.h, src/lib/comms/include/sol-coap.h, src/lib/comms/include/sol-http.h, src/lib/comms/include/sol-oic-server.h, src/lib/comms/sol-coap.c, src/lib/comms/sol-oic-server.c, src/lib/datatypes/include/sol-buffer.h, src/lib/datatypes/include/sol-str-slice.h, src/lib/io/include/sol-efivarfs-storage.h, src/lib/io/include/sol-fs-storage.h, src/lib/io/include/sol-memmap-storage.h, src/lib/parsers/include/sol-json.h, src/modules/flow/http-server/http-server.c, src/modules/flow/http-server/http-server.json, src/modules/flow/oauth/oauth.c, src/modules/flow/oauth/oauth.json, src/samples/flow/http-server/static-files.fbp, src/samples/oauth_twitter.fbp
from v1:
- Split the fixes in different commits
- Use some `#define` magics to not duplicate code
=> headers: Make headers buildable in C++ compiler v2

src/lib/common/sol-pin-mux.c, src/lib/common/sol-update.c
It was broken the log in pin-mux and update
=> Fix log domains

src/lib/comms/include/sol-http.h, src/lib/comms/sol-http-client-impl-curl.c, src/lib/comms/sol-http-common.c, src/lib/comms/sol-http-server-impl-microhttpd.c, src/modules/flow/http-client/http-client.c, src/samples/http/client.c
- [client] Handle post data correctly (using multipar/form-data)
- [client] Allows one send file contents just giving a file path
- [client] Add support multipar/form-data on sample
- [server] remove unused code
- [server] handle post data properly
=> Fixes http

src/lib/flow/sol-flow-packet.c
=> packet: Add missing packets to type_as_string()

src/modules/flow/iio/iio.json, src/modules/flow/iio/nodes.c
This PR supports Magnet , Pressure, Color , Huminity, Accelerate and ADC Category into iio node. And all the sensor category have been tested to work well in minnowmax using different sensors supported by their iio drivers.
=> support another 6 category sensors into soletta iio node

src/lib/comms/include/sol-http-server.h, src/lib/comms/sol-http-server-impl-microhttpd.c
=> http:server: Add api to set post data buffer size

src/lib/common/sol-bus.c, src/lib/common/sol-bus.h, src/lib/comms/include/sol-coap.h, src/lib/comms/include/sol-mavlink.h, src/lib/comms/include/sol-mqtt.h, src/lib/comms/include/sol-oic-client.h, src/lib/comms/include/sol-oic-server.h, src/lib/comms/sol-coap.c, src/lib/comms/sol-mavlink.c, src/lib/comms/sol-oic-client.c, src/lib/comms/sol-oic-server.c, src/lib/comms/sol-socket-impl-linux.c, src/lib/comms/sol-socket-impl-riot.c, src/lib/comms/sol-socket-impl.h, src/lib/comms/sol-socket.c, src/lib/comms/sol-socket.h, src/lib/datatypes/include/sol-vector.h, src/lib/datatypes/sol-vector.c
https://github.com/solettaproject/soletta/issues/1269
=> Normalizing user data pointer

src/modules/update/update-common/file.h
=> update: Fix 'C' linkage on header

src/shared/include/sol-util-file.h
from v1:
- Add where/when it is used
=> doc:util: Add missing doc

src/lib/common/sol-board-detect.c, src/lib/common/sol-log-impl-linux.c, src/lib/common/sol-platform-impl-linux-micro.c, src/lib/common/sol-platform-impl-systemd.c, src/lib/io/sol-gpio-impl-linux.c, src/lib/io/sol-pwm-impl-linux.c, src/modules/flow/power-supply/power-supply.c, src/modules/linux-micro/console/console.c, src/modules/linux-micro/locale/locale.c, src/modules/linux-micro/machine-id/machine-id.c, src/modules/pin-mux/intel-common/intel-common.c, src/modules/update/linux-micro-efi/linux-micro-efi-update.c
=> Add missing header sol-util-file.h

data/jsons/dependencies.json, tools/build/Makefile.vars
Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>
=> Check for the validity of the -soname flag before using

src/modules/flow/process/output.c
=> process: Add missing sol-util-file include

data/jsons/dependencies.json, src/lib/common/sol-mainloop-impl-posix.c
Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>
=> Add support for pollts as a replacement for ppoll

src/samples/common/linux-micro-init.c
=> samples:linux-micro: Do not redefine _GNU_SOURCE

src/lib/crypto/include/sol-message-digest.h
We have an API to create digests from user data, but we don't implment
any of that, so add some more clarification in the documentation about
how this works.
Signed-off-by: Iván Briano <ivan.briano@intel.com>
=> crypto: Add clarification about how the wrapper works

src/bin/sol-fbp-runner/main.c, src/lib/comms/sol-lwm2m.c
runner -> in a deep level, it can trigger sol-log before sol-init
+ warning removal
=> Simple fixes

src/lib/comms/sol-http-common.c, src/lib/datatypes/include/sol-buffer.h, src/lib/datatypes/sol-buffer.c, src/lib/io/sol-efivarfs-storage.c, src/lib/io/sol-fs-storage.c, src/lib/io/sol-iio.c, src/lib/io/sol-memmap-storage.c, src/modules/flow/unix-socket/unix-socket.c, src/samples/http/server.c, src/shared/include/sol-util-file.h, src/shared/sol-util-file.c, src/test/test-buffer.c
now for good, fixes the `sol_buffer_trim()` usage.
=> Mem fixes v3

src/lib/comms/include/sol-http-server.h, src/lib/comms/sol-http-server-impl-microhttpd.c, src/lib/datatypes/include/sol-buffer.h, src/lib/datatypes/sol-buffer.c, src/samples/http/Kconfig, src/samples/http/Makefile, src/samples/http/server-sse.c
from v4:
- s/response_progressive/progressive_response/g
- Fix documentation
- sample's buffer is local
- the connections are handled properly on CTRL-D
=> Http sse v5

src/lib/common/include/sol-types.h, src/lib/common/sol-types.c, src/lib/comms/include/sol-http.h, src/lib/comms/sol-http-common.c, src/lib/datatypes/include/sol-str-slice.h, src/lib/datatypes/sol-str-slice.c, src/lib/parsers/include/sol-json.h, src/modules/flow/http-client/http-client.c, src/modules/flow/http-client/http-client.json, src/modules/flow/http-server/http-server.c, src/modules/flow/http-server/http-server.json, src/test-fbp/http-allowed-methods.fbp, src/test-fbp/http-blob.fbp, src/test-fbp/http-boolean.fbp, src/test-fbp/http-drange.fbp, src/test-fbp/http-irange.fbp, src/test-fbp/http-sse.fbp, src/test-fbp/http-string.fbp, src/test/test-http.c, src/test/test-str-slice.c
Chances since v2:
* Added commit de7362a
* Added function `sol_json_scanner_init_from_slice()` - check  7aa1e5f
* Some other minor fixes pointed by @barbieri
=> Add SSE support for Soletta's HTTP nodes v3

src/lib/common/sol-mainloop-impl-riot.c, src/lib/comms/sol-socket-impl-riot.c
And a little fix for the socket implementation.
=> Change RIOT's main loop to match Zephyr's style

src/lib/comms/sol-socket-impl-zephyr.c
It receives references to {remote,local} addresses and expects them to
be reachable memory at all times (net_receive() and others will later
de-reference that memory). For some weird reason, Soletta did not crash
passing NULL to signal an all zeroed-out remote address and a stack
placed variable reference to the local one, beats us why.
=> zephyr: fix usage of net_context_get()

src/lib/comms/sol-socket-impl-linux.c, src/modules/flow/unix-socket/unix-socket-impl.c
@ceolin ptal
A commit on top of PR #1394
=> Fixes for PR 1394

doc/doxygen/Doxyfile, src/lib/common/Makefile, src/lib/common/include/sol-atomic.h, src/lib/common/sol-mainloop-common.c, src/lib/common/sol-mainloop-impl-posix.c, src/lib/common/sol-worker-thread-impl-glib.c, src/lib/common/sol-worker-thread-impl-posix.c, src/lib/common/sol-worker-thread-impl-riot.c
I've fixed a few issues in a commit on top of
PR #1244 commits
=> Fix issues on PR 1244

doc/doxygen/Doxyfile
Now we should be good on doxygen
=> sol-atomic: remove DOXYGEN_RUN usage

src/lib/datatypes/sol-memdesc.c, src/modules/flow/robotics/robotics.c
=> Fix compilation warnings.

data/scripts/sol-flow-node-type-aliases-gen.py.in
trying to fix build on semaphoreci
=> scripts/alias-gen: Set file encoding

doc/tutorials/ostro-oic-tutorial/.gitignore, doc/tutorials/ostro-oic-tutorial/step1/http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step1/tutorial.md, doc/tutorials/ostro-oic-tutorial/step2/http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step3/http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step3/oic-and-http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step3/persistence-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step3/tutorial.md, doc/tutorials/ostro-oic-tutorial/step4/http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step4/oic-and-http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step4/persistence-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step4/tutorial.md, doc/tutorials/ostro-oic-tutorial/step5/http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step5/oic-and-http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step5/persistence-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step6/http-controller.fbp, doc/tutorials/ostro-oic-tutorial/step6/http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step6/oic-and-http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step6/oic-controller.fbp, doc/tutorials/ostro-oic-tutorial/step6/persistence-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step6/sol-flow.json, doc/tutorials/ostro-oic-tutorial/step7/controller.fbp, doc/tutorials/ostro-oic-tutorial/step7/http-controller.fbp, doc/tutorials/ostro-oic-tutorial/step7/http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step7/oic-and-http-light-server.fbp, doc/tutorials/ostro-oic-tutorial/step7/oic-controller.fbp, doc/tutorials/ostro-oic-tutorial/step7/persistence-light-server.fbp
* many small issues on flows and explanation
* add missing flows on each step, so users can just run flows inside
the step dir
* add a .gitignore for persistence files
* rename files to match instructions / command lines
@ceolin @edersondisouza ptal asap ^
Thanks
=> ostro-tutorial: fix it

src/lib/common/sol-bus.c, src/lib/comms/sol-http-server-impl-microhttpd.c, src/lib/flow/sol-flow-composed.c, src/modules/flow/oauth/oauth.c, src/modules/flow/twitter/twitter.c
Fixes for problems spotted by Clang static analyzer.
=> Clang fixes

src/modules/flow/grove/grove.json, src/modules/flow/iio/iio.json, src/modules/flow/iio/nodes.c, src/modules/flow/piezo-speaker/piezo-speaker.json, src/modules/flow/si114x/si114x.c, src/modules/flow/si114x/si114x.json, src/modules/flow/temperature/temperature.json, src/samples/flow/iio/sol-flow-intel-minnow-max-linux_gt_3_17.json, src/samples/flow/iio/sol-flow.json
=> node-names: finish normalizing names and aliases

doc/js-spec/oic.md, src/lib/common/Kconfig, src/lib/common/include/sol-types.h, src/lib/comms/include/sol-oic-server.h, src/lib/io/include/sol-ipm.h, src/modules/flow/boolean/boolean.json, src/modules/flow/float/float.json, src/modules/flow/int/int.json, src/modules/flow/string/Kconfig, src/modules/flow/update/update.json, src/samples/flow/c-api/simplectype.c, src/samples/flow/js/attendee.fbp, src/samples/flow/js/attendee.js, src/samples/flow/js/mycounter.js, src/samples/flow/unix-socket/README, src/test-fbp/converter-int-direction-vector.fbp, src/test/test-str-slice.c
This patch fixes general typos
=> misc: Fix typos

src/lib/comms/include/sol-http.h, src/modules/flow/pwm/pwm.json, tools/build/Makefile.targets
=> Small changes related to recent prs

src/lib/common/include/sol-certificate.h, src/lib/common/sol-certificate-impl-linux.c
https://github.com/solettaproject/soletta/issues/1658
=> Certificate fixes

src/lib/comms/include/sol-http-client.h
=> http:doc: Add snippet

doc/doxygen/Doxyfile
=> doxygen: Add Soletta trademark in the header

tools/build/Makefile.targets
=> build: use syntax that works fine on bash or dash

src/samples/flow/iio/Makefile, src/samples/flow/iio/proximity.fbp, src/samples/flow/iio/sol-flow-intel-minnow-max-linux_gt_3_17.json, src/samples/flow/iio/sol-flow.json
Signed-off-by: Yong Li <yong.b.li@intel.com>
=> samples: add iio/proximity-sensor sample

data/scripts/libsoletta.sym, data/scripts/sol-oic-gen.py, src/lib/common/include/sol-util.h, src/lib/common/sol-util-internal.h, src/shared/sol-fbp-graph.c, tools/build/Makefile.rules
=> make sol-oic-gen quiet and fix build

src/lib/common/sol-platform.c, src/lib/common/sol-util-file.c, src/lib/datatypes/sol-buffer.c, src/lib/io/sol-pwm-impl-zephyr.c, tools/build/Makefile.rules
=> Fixes related to building Zephyr samples

src/lib/common/sol-platform-impl-zephyr.c, src/lib/comms/sol-network-impl-zephyr.c
Required to have samples working on this platform.
=> Zephyr implementation missing functions

src/modules/flow/iio/nodes.c
issue #2233
Signed-off-by: Yong Li <yong.b.li@intel.com>
=> iio: fix the logic error caused by code refactor

src/lib/comms/sol-lwm2m.c
=> LWM2M: Fix use-after-free.

src/modules/flow/calamari/calamari.c
=> modules/calamari: only check API version of used options

doc/js-spec/oic.md
=> docs: update links on oic js-spec documentation

src/samples/nodejs/aio_read.js, src/samples/nodejs/calamari.js, src/samples/nodejs/gpio_by_label.js, src/samples/nodejs/gpio_monitor.js, src/samples/nodejs/gpio_read.js, src/samples/nodejs/gpio_write.js, src/samples/nodejs/pwm_led.js, src/samples/nodejs/spi_max31855.js, src/samples/nodejs/uart_sample.js
=> Use TM instead of unicode on js files

data/scripts/libsoletta.sym, src/lib/comms/Makefile, src/lib/comms/include/sol-coap.h, src/lib/comms/include/sol-lwm2m-bs-server.h, src/lib/comms/include/sol-lwm2m-server.h, src/lib/comms/include/sol-lwm2m.h, src/lib/comms/sol-coap.c, src/lib/comms/sol-lwm2m-bs-server.c, src/lib/comms/sol-lwm2m-client.c, src/lib/comms/sol-lwm2m-common.c, src/lib/comms/sol-lwm2m-common.h, src/lib/comms/sol-lwm2m-security.c, src/lib/comms/sol-lwm2m-security.h, src/lib/comms/sol-lwm2m-server.c, src/lib/comms/sol-oic-security.c, src/lib/comms/sol-socket-dtls-impl-tinydtls.c, src/lib/comms/sol-socket-dtls.h, src/samples/coap/lwm2m-bs-server.c, src/samples/coap/lwm2m-client.c, src/samples/coap/lwm2m-server.c, src/test/test-lwm2m.c
Main changes since v2 (#2285):
https://github.com/solettaproject/soletta/pull/2285#discussion-diff-74800812
Signed-off-by: Bruno Melo bsilva.melo@gmail.com
=> LWM2M: Support for DTLS with Pre-Shared Key security mode [v3]

src/lib/comms/Kconfig, src/lib/comms/sol-lwm2m-bs-server.c, src/lib/comms/sol-lwm2m-client.c, src/lib/comms/sol-lwm2m-common.c, src/lib/comms/sol-lwm2m-common.h, src/lib/comms/sol-lwm2m-server.c, src/lib/comms/sol-socket-dtls-impl-tinydtls.c
Chances since v2:
* Properly check the path restrictions during bootstrap operations
=> Fixes lwm2m v3

src/modules/flow/netctl/netctl.c
Small fixes spotted by compiler
=> flow:netctl: fixes

src/modules/flow/iio/nodes.c
Add light/pressure support
Fix issue #2101
Signed-off-by: Yong Li <yong.b.li@intel.com>
=> iio: support of IIO sampling frequency to channel level

src/lib/io/include/sol-iio.h, src/lib/io/sol-iio.c, src/modules/flow/iio/iio.json, src/modules/flow/iio/nodes.c
Fix issue #1998
Signed-off-by: Yong Li <yong.b.li@intel.com>
=> iio: add support for multiple channels

src/lib/io/sol-iio.c
It allows using wildcard characters to select an IIO path. It's
important to know that only the first result is used.
It internally uses glob().
=> iio: Support wildcard in IIO path input
