- src/lib/flow/sol-flow-builder.c
Taking in consideration the last index of the previous port to set the
base port index.
> flow: Fix export port

- src/samples/flow/minnow-calamari/calamari-led.fbp
- src/samples/flow/minnow-calamari/calamari-lever.fbp
- src/samples/flow/minnow-calamari/sol-flow.conf
Both calamari-led and calamari-lever were using the same
lever config, however max=1000 was valid only for
calamari-led.
Signed-off-by: Anselmo L. S. Melo <anselmo.melo@intel.com>
> minnow-calamari: Make lever sample work again

- src/bin/sol-fbp-generator/type-store.c
Due to a bug in JSON parsing, '(null)' was being placed instead.
> fbp-generator: fix range and rgb default value parsing in type store

- src/bin/sol-fbp-generator/type-store.c
Due to a bug in JSON parsing, '(null)' was being placed instead.
> fbp-generator: fix direction vector default value parsing in type store

- src/lib/flow/sol-flow-builder.c
This was making the joint of .conf and .fbp node options impossible.
> sol-flow-builder: Fix wrong pointer arithmetic.

- tools/build/Makefile.rules
The ubuntu 14.04 linker will not work if the libs are not the last arguments.
> kbuild: fix issue with ubuntu 14.04

- src/lib/common/sol-bus.c
- src/lib/common/sol-bus.h
- src/lib/common/sol-platform-impl-systemd.c
Starting with systemd 221, sd-bus is officially supported and the
signature of the functions changed from the ones we were using.
> Fix signature of sd-bus functions now that it's officially supported

- src/lib/common/Kconfig
All the other options are sorted alphabetically.
Also using dummy as default instead of micro-linux
seems more straighforward for general users.
> kconfig: sort platform options and select dummy as default

- src/lib/common/Kconfig
- src/lib/common/Makefile
- src/lib/common/sol-mainloop-impl-posix.c
- src/lib/common/sol-worker-thread-impl-glib.c
- src/lib/common/sol-worker-thread-impl-posix.c
- src/lib/common/sol-worker-thread-impl.h
- src/lib/common/sol-worker-thread.c
- src/lib/common/sol-worker-thread.h
- src/shared/Kconfig
- src/shared/Makefile
v5:
- rebased and ported to Kbuild
v4:
- rebased
v3:
- use atomic inc to maintain the static counter consistent among threads
v2:
- added simple static counter for setting glib worker threads' names
> worker-threads: move to common and organize different implementations

- src/lib/flow/sol-flow-builder.c
When we copy the defaults from an actual options struct, we need to
ensure we only read the real size of the type.
> Fix invalid read reported by valgrind

- Makefile
- tools/build/Makefile.targets
The builtins.json file was being generated only on install target,
we must generate it while building.
> builtins.json: we should generate it on build

- src/samples/flow/foosball/foosball.fbp
boolean/* nodes now use array ports. This samples wasn't
properly updated accordingly.
Signed-off-by: Anselmo L. S. Melo <anselmo.melo@intel.com>
> Fix foosball.fbp after changes in boolean nodes

- src/samples/flow/galileo-grove-kit/grove-temperature-sensor.fbp
- src/samples/flow/misc/tickets_queue.fbp
Fix samples that use boolean/* and string/* node types. Update their code to use array ports.
> Fix samples that should be using array ports

- tools/build/Makefile.vars
The oic generator targets were in race condition since it's a pre
generation dependency and the modules' itself. Both could have their
execution in clash and break the oic module's source code generation;
This patch removes the pre generation condition and leave it up to
the module to directly depend on it and require its generation up
to their build conditioning.
> build: fix oic generator race condition

- src/shared/sol-fbp-parser.c
strerror() should never be used in Soletta.
sol_util_strerrora() is a wrapper for that that's always
threadsafe, regardless of implementation details.
> parser: use sol_util_strerrora() instead of strerror()

- src/bin/sol-fbp-generator/main.c
Differences from v1:
- start using mkostemp()
- don't use O_TMPFILE and linkat() and use temporary file and rename instead.
- use sol_util_strerrora()
Before this patch, we were appending to the output file piece by
piece, at the risk of generating the output file by half if the
generation fails at some part.
Now we're creating a temporary file and when the generation ends,
we rename to a filepath that the user provide us.
> fbp-generator: write to a temporary file until the generation ends v2

- src/bin/sol-fbp-generator/main.c
Rename will already replace the old file to the generated file,
there's no need to remove it before.
> fbp-generator: remove useless old file removal

- src/bin/sol-fbp-generator/main.c
> fbp-generator: fix printf arg type mismatch on error message

- src/bin/sol-fbp-generator/main.c
- src/bin/sol-fbp-generator/type-store.c
- src/bin/sol-fbp-generator/type-store.h
Differences from v1:
- each generated fbp type has its own type store and the JSONs will be stored in a common type store.
- changed the generated C code, to split the creation of fbp type into functions, creating them recursively.
Now the generator handles the declaration and usage of new types in the FBP itself.
e.g.
DECLARE=MyType:fbp:my-type.fbp
my_node(MyType) OUT -> ...
In the generated C code now, we split the creation of fbp types into functions, creating them recursively.
> fbp-generator: add support for DECLARE statement v2

- src/lib/flow/sol-flow-buildopts.h.in
It was depending of a header that is not installed.
> build: Fix the build of external modules

- tools/build/Makefile.vars
Differences from v1:
- lgcov passed to COMMON_LDFLAGS instead.
@dorileo asked me to also include 'COMMON_LDFLAGS += $(LDFLAGS)' to
this file since the build system wasn't considering flags passed by the user.
> coverage: fix 'make coverage' v2

- tools/build/Makefile.rules
When compiling the tests, we were adding more flags than needed, in
particular all-ldflags and all-cflags, that have all the flags that were
encountered.
After:
molly soletta > ldd ./src/test/test-vector
linux-vdso.so.1 (0x00007ffe519c2000)
libglib-2.0.so.0 => /usr/x86_64-pc-linux-gnu/lib/libglib-2.0.so.0 (0x00007f4c7e445000)
libpthread.so.0 => /usr/x86_64-pc-linux-gnu/lib/libpthread.so.0 (0x00007f4c7e228000)
libm.so.6 => /usr/x86_64-pc-linux-gnu/lib/libm.so.6 (0x00007f4c7df2b000)
libdl.so.2 => /usr/x86_64-pc-linux-gnu/lib/libdl.so.2 (0x00007f4c7dd27000)
libc.so.6 => /usr/x86_64-pc-linux-gnu/lib/libc.so.6 (0x00007f4c7d984000)
/usr/x86_64-pc-linux-gnu/lib/ld-linux-x86-64.so.2 (0x00007f4c7e77c000)
Before:
molly soletta > ldd ./src/test/test-vector
linux-vdso.so.1 (0x00007ffd7ebf5000) …
> build: Remove unnecessary flags when compiling tests

- src/test/Makefile
- tools/build/Makefile.rules
- tools/build/Makefile.vars
We have 2 categories of tests, one testing the public exported API's
and those testing the "internal API's", the current only internal test
implementation is test-coap.
This patch introduces a differentiation for the mentioned categories.
Tests using the public API are now linked to libsoletta.so and uses
only objects exported there, the internal ones have access to any part
of internal symbols, so they can test any part of it.
> build: split internal tests

- data/jsons/dependencies.json
- src/shared/sol-util-linux.c
Instead of using paths relative to the binary that is being run, this series proposes a way to find the path relative to the libsoletta.so library. This solves the problem when running the binaries under gdb, sudo, and so on.
> More robust way to get the rootdir

- .gitmodules
- data/scripts/git-init-submodules.py
- src/lib/flow/Kconfig
- src/lib/flow/Makefile
- src/lib/flow/include/sol-flow-js.h
- src/lib/flow/sol-flow-js.c
- src/lib/flow/sol-flow-parser.c
- src/samples/flow/js/attendee.fbp
- src/samples/flow/js/attendee.js
- src/samples/flow/js/mycounter.fbp
- src/samples/flow/js/mycounter.js
- src/samples/flow/js/splitter.js
- src/samples/flow/js/telegram.fbp
- src/samples/flow/js/telegram.js
- src/test-fbp/javascript.fbp
- src/test-fbp/javascript.js
- src/test/.gitignore
- src/test/Kconfig
- src/test/Makefile
- src/test/test-javascript.c
- src/thirdparty/Makefile
- src/thirdparty/README
- tools/build/Makefile.rules
- tools/build/Makefile.targets
- tools/build/Makefile.vars
Differences from v2:
- use git modules to get duktape sources ( @dorileo helped me a lot, thanks! )
- fixed typo in warning message
DIfferences from v1:
- start raising javascript exceptions in error cases
- start comparing packet type pointers in `send_packet()`
- remove useless `| 0` in `duk_def_prop()` flags
- create auxiliary functions to process functions
- use `strndupa()` instead of `sol_arena_strdup_slice()` in `create_js_type()`
- small changes on samples
This series introduce Javascript node using Duktape[1] as third party library,
allowing the usage of Javascript language to create new and customizable node types.
The aim of this series is to introduce an initial support for Javascript nodes, there is
other features that we'll add later on.
A JS node type is specified with one …
> Soletta meets JS v3

- src/modules/flow/accelerometer/lsm303.c
It was missing a 'break'. Found by coverity.
> lsm303: Fix switch clause on accelerometer/lsm303

- src/lib/io/include/sol-uart.h
- src/lib/io/sol-uart-linux.c
- src/lib/io/sol-uart-riot.c
- src/modules/flow/piezo-speaker/piezo-speaker.c
- src/samples/common/uart.c
Changes from V3:
- Added documentation to all UART functions
- Squashed 'UART: Fix callback parameter order' into 'UART: Simplify API'
- Changed tx buffer and received byte to unsigned char, as it is not necessary a character.
- Making user responsible to handle tx buffer allocation.
> UART: Simplify API V4

- src/lib/io/include/sol-spi.h
- src/lib/io/sol-spi-linux.c
- src/lib/io/sol-spi-riot.c
- src/modules/flow/calamari/calamari.c
- src/modules/flow/led-strip/lpd8806.c
Changes from V1:
- Removed SPI_SPEED enum, going back to uint32_t to give user more flexibility
- Using timeout_add(0,...) instead of idle_add()
- Added more information on documentation
> SPI refactor V2

- src/lib/common/sol-missing.h
That file should never have been documented. It was by mistake, since it
was erroneously installed at the time.
> Undocument missing.h.

- data/oic/oicgen.py
- src/lib/flow/sol-flow-node-options.c
- src/modules/flow/converter/converter.c
- src/modules/flow/freegeoip/freegeoip.c
- src/modules/flow/test/float-generator.c
- src/modules/flow/test/float-validator.c
- src/shared/sol-util.c
- src/shared/sol-util.h
This PR has a bunch of minor fixes, including some low-priority Coverity warnings in the recently-added `freegeoip` module, using the new JSON number parsing routines in the `oicgen.py` script, and using `sol_util_strtodn()` where `strtod()` was used before.
> Random fixes

- Kconfig
- data/jsons/dependencies.json
- tools/build/Makefile.vars
This patch brings back the -fsanitize flags. It adds the CC_SANITIZE
item to Kconfig and the sanitize type dependent to it. The default (like
previously with autotools) is -fsanitize=undefined, unless disabled or
non supported.
> build: bring back -fsanitize=address|undefined flags

- Makefile
- tools/build/Makefile.common
- tools/build/Makefile.rules
- tools/build/Makefile.vars
- tools/check-license.sh
+ v2 (since #572):
- added patch: **	check-license: ignore makefiles**;
- added patch: **	build: generate soletta.pc on build time**;
+ v3 (since #573):
- changed the Makefile ignore rule in: **check-license: ignore makefiles**;
+ v4 (since #574):
- changed patch: **check-license: ignore makefiles** to really fix the issue with check-license.sh on tree, it was considering Makefile.common case the grep was ```.*\.[ch]``` not ```.*\.[ch]$```;
- upstream rebased;
**PS**: Since this series has got an ack in the previous version I'm sending this version simply to shoot the build bots and have one last check;
> Build general improvements v4

- tools/build/Makefile.rules
Since we're now calling kconfig/conf the rule should make sure it's
built. This patch does that by implicitly declaring it as its dependency.
> build: make sure we've kconfig/conf built

- src/modules/pin-mux/intel-edison-rev-c/intel-edison-rev-c.c
The correct ADC device should be always 1.
Signed-off-by: Murilo Belluzzo <murilo.belluzzo@intel.com>
> pin-mux: Fix missing 'hole' in Edison AIO vector

- data/scripts/gen-release-note.sh
So we can list issues closed after some specific date.
It requires a newer version of my fork of git-hub:
https://github.com/bdilly/git-hub
> scripts/gen-release-note: support options to fetch "closed after"

- src/modules/flow/persistence/fs-storage.c
File was not being closed upon write failure.
Thanks to coverity.
> persistence: Fix resource leak

- src/lib/common/sol-platform-impl-linux-micro.c
- src/lib/common/sol-platform-impl-systemd.c
- src/modules/linux-micro/machine-id/machine-id.c
The rest of the calls are fine, it seems.
> Fix limited string size reads with sol_util_read_file() calls.

- data/jsons/dependencies.json
+ v2 (since #702)
- fixed s/asan/ubsan/;
- removed san intrumentation for no-san option;
In the commit 202bff12f21b114d39b818b887ff94771a034c4d we changed the
sanitze dependencies to also force linking against libasan - in the
commit message we state that this would be harmless to newer gcc
versions. I turns out not to be true, if we're linking against the
shared libasan we should make sure to preload the lib or make sure it is
the first DSO name[1].
To avoid this kind of runtime issues we're forcing libasan to be
statically linked.
[1] -
https://github.com/gcc-mirror/gcc/blob/master/libsanitizer/asan/asan_linux.cc#L112
> build: link to static libasan

- src/lib/flow/sol-flow-resolver-conffile.c
- src/modules/flow/float/float.c
- src/modules/flow/float/float.json
- src/samples/flow/galileo-grove-kit/grove-led-wave-generator.fbp
- src/samples/flow/galileo-grove-kit/lcd/grove-lcd-fade.fbp
- src/shared/sol-conffile.c
- src/test-fbp/wave-generator.fbp
- src/test/test-flow-builder.c
- src/test/test-flow-parser.c
Fix the checks for allmodconfig, basically. Tested also with
allyesconfig and alldefconfig, all work. User configurations still have
the potential to break due to assumptions from the tests that certain
node-types will be available always.
> Ensure make check{,-fbp,-fbp-bin} work on non default configurations

- src/shared/sol-conffile.c
filename was leaking in case of sol_file_reader_open() returns NULL.
> conffile: Fix memory leak

- src/lib/flow/include/sol-flow.h
- src/test/test-flow.c
- tools/build/Makefile.targets
If node type description is not enabled the function
sol_flow_node_named_options_parse_member() is never run and its prototype
becomes broken since struct sol_flow_node_options_member_description is
never declared in that case.
Also the sol-fbp-runner and sol-fbp-generator both depend on description
if it's not present the targets check-fbp and check-fbp-bin should never
run due the lacking of the over mentioned binaries.
In the test/sol-flow.c we should also not build the description tests if
it's not enabled, otherwise the tests will fail at all.
> flow: fix issues when node type desc is not enabled

- src/modules/flow/converter/string-format.c
Do this not only in the case where there's an exponent.
> flow/string-format: Also ensure that precision == 0 is valid in another case

- src/bin/sol-fbp-generator/main.c
It was being included every time Soletta has support for
memmap-storage, regardless of whether the FBP uses it or not, which
makes generating programs for cross-building problematic.
Also, include errno.h always, as the composed node types generate code
using ENOMEM. Previously it was working because memmap-storage includes
sol-buffer.h, which includes errno.h.
> fbp-generator: Don't include memmap-storage header if not needed

- src/modules/flow/float/float.c
- src/test-fbp/persistence-fs-1.fbp
- src/test-fbp/persistence-fs-2.fbp
- src/test-fbp/persistence-memmap-1.fbp
- src/test-fbp/persistence-memmap-2.fbp
As long double is not always bigger than double, we now do the
calculations without need for a bigger temporary storage.
The idea is to find the distance to interval midpoint on input, and
replicate this distance on output interval. This restric calculations to
normal double variables.
> float: New way to map irange values - no need for long double

- src/bin/sol-fbp-generator/Kconfig
The generator code needs the flow support, it will not compile if flow
is disabled since it requires sol-flow-static.h and sol-flow-metatype.h
due the use of SOL_FLOW_NODE_PORT_ERROR_NAME, SOL_FLOW_NODE_PORT_ERROR
and so on.
> generator: it depends on flow, so enforce this dep

- data/jsons/dependencies.json
mosquitto_lib_init() is not enough to check for the proper version of
libmosquitto since it has the same signature in incompatible versions.
mosquitto_opts_set is a new API added in mosquitto 1.4. All versions
after 1.4 are compatible with soletta.
Signed-off-by: Rodrigo Chiossi <rodrigo.chiossi@intel.com>
> mqtt: Fix dependency check for libmosquitto

- tools/build/Makefile.rules
If we have an obj-something built as a module, and optional
dependencies that are always built-in, the mismatch in
obj-something-m-extra-cflags and obj-something-y-extra-cflags could
break the build.
Allow these dependencies to be added to the base obj without requiring
cumbersome Makefile conditionals.
Signed-off-by: Iván Briano <ivan.briano@intel.com>
> build: Be more permissive about extra-{c,ld}flags

- src/lib/common/include/sol-log.h
- src/lib/common/sol-pin-mux.c
- src/lib/flow/sol-flow-builder.c
- src/lib/flow/sol-flow-packet.c
- src/lib/flow/sol-flow-parser-dynamic.c
- src/lib/flow/sol-flow-resolver-conffile.c
- src/modules/flow-metatype/js/js.c
- src/modules/flow/accelerometer/adxl45.c
- src/modules/flow/accelerometer/lsm303.c
- src/modules/flow/aio/aio.c
- src/modules/flow/am2315/am2315.c
- src/modules/flow/converter/converter.c
- src/modules/flow/grove/grove.c
- src/modules/flow/gyroscope/gyroscope.c
- src/modules/flow/location/location.c
- src/modules/flow/magnetometer/lsm303.c
- src/modules/flow/platform/platform.c
- src/modules/flow/pwm/pwm.c
- src/modules/flow/string/string-ascii.c
- src/modules/flow/string/string-icu.c
- src/modules/flow/string/string-regexp.c
- src/modules/linux-micro/hostname/hostname.c
- src/modules/pin-mux/intel-common/intel-common.c
Also, add a macro to make it easier to have a custom wrn msg on null checks, when apply this macro as many places I could.
Motivation was that we were slowing removing many 'SOL_NULL_CHECKS' just in order to improve our logging messages,
> Improve warning about node not found in module

- src/shared/sol-util.c
./src/shared/sol-util.c: In function ‘sol_util_uuid_gen’:
./src/shared/sol-util.c:310:12: warning: missing braces around
initializer [-Wmissing-braces]
struct sol_uuid uuid = { 0 };
> shared: fix warning on sol-util

- src/lib/comms/sol-socket-impl.h
- src/lib/comms/sol-socket.c
./src/lib/comms/sol-socket-impl.h:57:7: warning: "SOL_PLATFORM_RIOT" is not defined [-Wundef]
#elif SOL_PLATFORM_RIOT
> Fix undefined symbol

- tools/build/Makefile.rules
When running make even without '-j', FLOW_OIC_GEN rule runs in parallel
with the remaining of Soletta build and was providing 'sol_config.h'
before it was needed most of the time and the build worked. But that
wasn't always the case, which was causing the build to fail for some
users.
This patch adds 'KCONFIG_AUTOHEADER' as dependency for remaining of the
build so it's always there when is needed. This also add a message when
'sol_config.h' is generated to make debug easier.
Signed-off-by: Murilo Belluzzo <murilo.belluzzo@intel.com>
> build: Fix race condition about 'sol_config.h'

- data/scripts/sol-flow-node-type-gen-html.py
Otherwise it may break the generated page.
> scripts/gen-html: escape double quotes on default values

- src/lib/comms/sol-http-common.c
- src/lib/datatypes/sol-buffer.c
- src/samples/coap/simple-server.c
A buffer shall use `sol_util_secure_clear_memory` only if
SOL_BUFFER_FLAGS_CLEAR_MEMORY flag is set.
However, current comparison had a mistake, as this flag contains
SOL_BUFFER_FLAGS_MEMORY_NOT_OWNED bits, so it was taking not owned as
requiring secure free.
Shall fix segfaults on make samples.
> buffer: Only perform 'clear memory' if buffer has requested so

- src/lib/comms/Kconfig
- src/test/Kconfig
test_http should depends on HTTP, not NETWORK
The common module of HTTP doesn't depends on any
external stuff, it could be enabled and tested
even if no dependencies are met for client or server.
Issue spotted by Lei A Yang <lei.a.yang@intel.com>
> lib/http: Fix build of library and tests

- src/lib/comms/sol-coap.c
In commit 386ee723 function packet_extract_path was changed to receive a
pointer to a string instead of returing the result string. In this new
function, the string was incorrectly accessed when adding '\0' and
invalid memory access was occuring.
Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>
> coap: Fix incorrect way of accessing a string position

- data/scripts/sol-oic-gen.py
device_id is not a pointer and should not be freed.
> scripts:oicgen: Remove wrong free

- src/lib/flow/include/sol-flow.h
- src/lib/flow/sol-flow-modules.c
Some nodes can have their own custom packets, it's necessary something
that allows one use them in different nodes even when they are not build static.
> flow: Add helper to load packet types

- src/lib/comms/sol-mavlink.c
mask can be used without be initialized.
> mavlink: Fix uninitialized variable

- src/lib/common/sol-mainloop-impl-posix.c
- src/lib/common/sol-platform-linux-common.c
- src/modules/flow/process/subprocess.c
Since Soletta is meant to be thread-safe, this is required. pipe(2) is
not thread-safe therefore it MUST NEVER be used in a threaded
application.
It's ok to use it in the child process between fork(2) and execve(2).
> Use pipe2(2) instead of pipe(2)

- src/lib/common/include/sol-glib-integration.h
- src/lib/common/include/sol-mainloop.h
- src/lib/common/sol-bus.c
- src/lib/common/sol-mainloop-common.c
- src/lib/common/sol-mainloop-impl-glib.c
- src/lib/common/sol-mainloop-impl.h
- src/lib/common/sol-mainloop.c
- src/lib/common/sol-platform.c
- src/lib/common/sol-update.c
- src/lib/datatypes/include/sol-vector.h
- src/lib/datatypes/sol-vector.c
- src/lib/flow/sol-flow-parser-dynamic.c
- src/shared/sol-conffile.c
- src/test/Kconfig
- src/test/Makefile
- src/test/test-mainloop-implementation.c
- src/test/test-mainloop-linux.c
- src/test/test-mainloop.c
- src/test/test-vector.c
Changes since v2 (#1226):
- rebased to master
- C++ fixes
@ceolin will add a `make check-cxx` that will get all of our public headers, include them and compile with C++, this will avoid problems like that in the future. Grantes we still need to use some macros in that test, so the code expands, I spotted our `_FOREACH` macros would fail with C++.
> Mainloop improvements v3

- src/lib/common/include/sol-log.h
It would fail if in SOL_INT_CHECK or SOL_EXP_CHECK the expression
contains '%' char.
> log: Fix invalid expression

- src/lib/comms/sol-socket-impl-linux.c
> sol-socket: Convert from sol_to_af before using it.

- src/lib/common/include/sol-log.h
check-cpp is failing without this.
> log: Add missing header

- src/lib/comms/sol-oic-server.c
As coap is now setting correct msg type in sol_coap_packet_new we
no longer need to set it in sol-oic-server.
Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>
> oic: Don't override response msg type set by coap lib

- src/modules/flow/form/form.c
sol_buffer_init was being called inside a loop causing the previous
allocated data being lost.
> form: Fix memory leak

- src/modules/flow/converter/converter.c
- src/modules/flow/converter/string-format.c
You can't pop without pushing first. Clang complains:
warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
> Add missing #pragma GCC diagnostic push

- Makefile
- tools/build/Makefile.rules
POSIX echo has no options. Otherwise, we get output like:
-e The following (required) dependencies were not met:
-e python module: jsonschema
-e If you've just installed it, run: make reconf
-e For more information/options, run: make help
> Remove -e from echo

- src/modules/flow/process/subprocess.c
This function doesn't return, so add the attribute.
Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>
> Fix Clang warning -Wmissing-noreturn

- data/jsons/dependencies.json
- tools/build/Makefile.vars
Prevent excess precision on non 64 machines, this may lead to
wrong results.
> Build: Set -ffloat-store on non 64 bits architetures.

- src/lib/comms/Makefile
There are a lot of warnings that are disabled when building tinydtls
that should not be used in soletta.
> comms:build: Preserve soletta flags

- .gitmodules
We shouldn't change submodules.
At the moment, they'll be showed as dirty,
listed as untracked content after a build, because
some of them will generate objects on these directories.
> submodules: ignore dirty submodules

- src/lib/common/Makefile
- src/lib/comms/sol-lwm2m.c
- src/modules/flow/float/Makefile
- src/modules/flow/trigonometry/Makefile
- Headers not utilized are breaking zephyr build
- Linking with libmath when necessary
> build  fixes

- tools/build/Makefile.rules
- tools/build/Makefile.vars
Given how JS nodes, converted to C by sol-fbp-generator, require that
duktape.c is built along, we also need to pass appropriate LDFLAGS,
namely in this case, -lm.
> check-fbp-bin: Fix building the javascript test

- src/lib/comms/sol-network-impl-riot.c
There is no such function sol_buffet_at_end in Soletta
> comms: replace sol_buffet_at_end to sol_buffer_at_end

- pc/soletta.pc.in
- tools/build/Makefile.vars
This allows us to use
build/soletta_sysroot/$PREFIX/lib/pkgconfig/soletta.pc while it's not
installed by calling:
```sh
export BUILT_PREFIX=$PWD/build/soletta_sysroot/$PREFIX
export PKG_CONFIG_PATH=$BUILT_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
pkg-config --cflags --libs --define-variable=prefix=$BUILT_PREFIX soletta
```
This may be required to simulate out-of-tree builds without installing
it.
Signed-off-by: Gustavo Sverzut Barbieri gustavo.barbieri@intel.com
> soletta.pc: use paths relative to variables.

- src/lib/comms/coap.c
@ceolin, could you verify this? It is related to your PR https://github.com/solettaproject/soletta/pull/1515
> Remove platform dependent code from coap.c

- src/modules/pin-mux/intel-edison-rev-c/intel-edison-rev-c.c
Some OS didn't like "double export". It wasn't an issue in the original image.
> pinmux: Change Edison Arduino breakout detection

- src/lib/comms/include/sol-coap.h
- src/lib/comms/sol-coap.c
- src/lib/comms/sol-oic-cbor.c
Some memory usage revamps.
-----------
Changes since v1:
- bad mem access fixed (ptr vector instead of vector for contexts)
Changes since v2:
- early continue on a func, to diminish nesting.
Changes since v3:
- Fixed the way new tokens were written to the original packet
- Kept a way to send notifications *with* confirmation, if the user wants to
Changes since v4:
- @vcgomes's approach to notifications packet reuse was taken
- fixed keeping context for ack/reset packets
- we don't keep context for noncon packts anymore
Changes since v5:
- new patch dealing with NONCON but with reply messages.
Changes since v6:
- new approach by @vcgomes on pending timeouts, with fixes
@edersondisouza's code sending a lot of con packets was his timers on neighbour discovery/scan. Those are being acked at …
> Coap mem improvements [v7]

- src/modules/flow/unix-socket/unix-socket-impl.c
'sol_vector_del()' should not be used when transversing the vector using
SOL_VECTOR_FOREACH_IDX() when multiple removals are possible.
Signed-off-by: Vinicius Costa Gomes <vinicius.gomes@intel.com>
> Fix usage of sol_vector_del()

- src/lib/io/include/sol-spi.h
This removes an unneeded header include from sol-spi.h and
also fixes a minor error in the API documentation.
Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>
> Remove unneeded header include from sol-spi.h

- src/lib/io/sol-iio.c
Otherwise after using a Soletta application the following
issue should happen when trying to access it:
root@edison:/sys/bus/iio/devices/iio:device1# cat *raw
cat: in_voltage0_raw: Device or resource busy
cat: in_voltage1_raw: Device or resource busy
cat: in_voltage2_raw: Device or resource busy
@edersondisouza could you please confirm that?
I didn't try to reproduce this issue (or fix), but
doing some code browsing the reason to stay busy
is thanks to buffer keep set as enabled.
Thanks
> lib/sol-iio: release buffer on sol_iio_close()

- src/lib/comms/sol-coap.c
CID 143930.
Since sol_socket_sendmsg()'s return type changed to ssize_t and it's
we're now storing its return value on ret var, fix the error check below
it.
> coap: fix coverity-pointed error

- data/scripts/sol-oic-gen.py
It was passing wrong parameters to create the code
Closes gh-1897
> oic-gen: fix rep_vec issue

- data/scripts/sol-oic-gen.py
Read Only property was incorrectly handled in code generation and some functions were being called when they shouldn't
> oic-gen: Fix invalid code generation

- bindings/nodejs/tests/getresult.js
- bindings/nodejs/tests/setup.js
Update the code #1856
- Generate a json file to collect the test results.
- Locate easily the failed tests in result file when using the results file
- Quickly generate results to match the specified format that QA required
- JSON dose not need to take up extra workspace.
Signed-off-by: Wang Hongjuan <hongjuan.wang@intel.com>
> Parse the test cases results log by json [v2]

- data/scripts/dependency-resolver.py
Yocto's TARGETCC does not only contain the compiler information but yet it
comes with some flags to crosscompile.
Example:
TARGETCC=i586-ostro-linux-gcc -m32 -march=i586 -Wa,-momit-lock-prefix=yes
> dependency-resolver: split args to parse the compiler name for Yocto

- data/scripts/dependency-resolver.py
The shlex split will be able to parse correctly in case of flags like the
following:
-DX="a b"
> dependency-resolver: replace the use of split to shlex.split.

- src/modules/flow/hc-sr04/hc-sr04.c
- src/modules/flow/hc-sr04/hc-sr04.json
No use cases for some pins on raw mode and other
on label mode.
So let's make it simpler to users.
> modules/hc-sr04: expose a single 'raw' option for both pins

- bindings/nodejs/tests/invasive-tests/Main Loop Integration.js
Signed-off-by: Gabriel Schulhof <gabriel.schulhof@intel.com>
Replaces #1972 
Additionally fixes the situation where an async callback is being called twice.
> Node.js bindings: Add sudo to invasive tests only if euid is not root

- data/jsons/dependencies.json
- data/scripts/dependency-resolver.py
Add options to check for specific exec versions.
Require at least LTS version of node (v4.4.4).
On old versions, like v0.10.x it wasn't able to build,
it was re-triggering builds on loop.
@glima please review it when possible ^
> scripts/dependency-resolver: check for exec versions

- src/lib/common/sol-mainloop.c
We can't use sol-log.h primitives since sol_init() wasn't called, so
proceed without logs.
> sol_mainloop_set_implementation() is called before sol_init(), no logs allowed.

- src/lib/io/sol-ipm.c
It was missed on blob type changes.
> ipm: Use SOL_BLOB_TYPE_NO_FREE_DATA on sent blob wrapper

- src/shared/sol-conffile.c
When mistakenly  SOL_FLOW_MODULE_RESOLVER_CONFFILE is set empty
the WRN message that is sent is clueless.
Example:
WRN: ./src/shared/sol-util-file.c:209 sol_util_load_file_fd_buffer() r (-1) < 0
WRN: ./src/shared/sol-util-file.c:181 sol_util_load_file_fd_raw() r (-1) < 0
WRN: ./src/shared/sol-util-file.c:209 sol_util_load_file_fd_buffer() r (-1) < 0
WRN: ./src/shared/sol-util-file.c:181 sol_util_load_file_fd_raw() r (-1) < 0
WRN: ./src/shared/sol-util-file.c:209 sol_util_load_file_fd_buffer() r (-1) < 0
WRN: ./src/shared/sol-util-file.c:181 sol_util_load_file_fd_raw() r (-1) < 0
This patch instroduces a warning telling that the
SOL_FLOW_MODULE_RESOLVER_CONFFILE should not be empty.
> sol-conffile: warn if SOL_FLOW_MODULE_RESOLVER_CONFFILE is empty

- src/lib/comms/sol-coap.c
It fixes the build when SOL_API_VERSION is disabled.
> coap: Fix build

- bindings/nodejs/configure-bindings.js
- bindings/nodejs/src/sys-constants.cc
- bindings/nodejs/src/sys-constants.h
- lowlevel.js
Also reverse-maps them for use in the bindings
We need these constants to return more legible errors from the bindings.
> Node.js bindings: Organize node.js system constants like errno

- tools/build/Makefile.targets
Signed-off-by: Gabriel Schulhof <gabriel.schulhof@intel.com>
@nagineni does this fix the problem with the integration?
> Build: Prevent node.js build from re-running during install

- Kconfig
Depending on how an OS builds for native, Soletta may still pass the
Linux detection test. Leaving Linux as the last OS to check for in
Kconfig allows any other OS to be used regardless of that test.
> build: Change OS selection order to prioritize small OSes

- Makefile
- tools/build/Makefile.targets
Otherwise it may lead to situations where the users used
by make and make clean diverge from make install and
clean can't actually remove the whole build directory.
Close gh-1536
> build: avoid files moved to build_dir on installing phase

- src/lib/comms/sol-oic-server.c
The client address pointer given by CoAP cannot be stored in the OIC request
because it points to a stack variable and thus cannot be used asynchronously.
The client address must be copied into the request structure instead.
Fixes gh-2125
Signed-off-by: Gabriel Schulhof <gabriel.schulhof@intel.com>
@otaviobp please review!
> OIC Server: Copy client address into request

- src/modules/flow/accelerometer/lsm303.c
- src/modules/flow/jhd1313m1/jhd1313m1.c
Since last change from patch 026c6f6945998ee1b365e8bb7f20e556f42efba4 the
function sol_i2c_set_slave_address does not return bool and yet it returns
a -ERRNO informing the probable cause of the error.
Thus the module should use in the same way instead of checking if false.
> check if sol_i2c_set_slave_address returns -ERRNO

- src/lib/common/sol-platform-linux-common.c
> sol-platform: allow spaces before '#' on conf comments

- src/lib/common/sol-platform.c
When SOL_FEATURE_FILESYSTEM is set, we don't need to use the default
app name, so move this code to #else section.
Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>
> platform: Remove unreachable code

- doc/node-types-html/css/main.css
- doc/node-types-html/index.html.in
After opening a nodetype and clicking in the nodetypes list, the navigation was
invalid.
In this patch, the back action is executed before selecting the nodetype in the
list thus the nodetype will be valid to be selected.
Difference from V1:
- Fix Firefox compability as pointed by @bdilly (Thanks!)
- Add commit that warns when the selected node has no examples to be shown. Also, the Get Code Button will get hidden.
> cheat-sheet: fix broken links that was not pointing to the nodelist - V2

- src/lib/datatypes/include/sol-memdesc.h
- src/lib/datatypes/include/sol-str-table.h
- src/lib/parsers/include/sol-json.h
- tools/build/Makefile.vars
Previous patch: https://github.com/solettaproject/soletta/pull/2195
Differences from V1:
- Fix build error caught by CI, Instead of removing the stage/include dir from HEADERDIRS we add it only if OIC is enabled since, it is the only module that needs the folder to be created.
------
This patchset includes 2 commits:
1- Fixes the warning: ./build/stage/include/: No such file or directory
[-Wmissing-include-dirs]
2- Fixes the warning: nonnull argument ‘value’ compared to NULL [-Wnonnull-compare]
> Fix warnings in build - V2

- src/modules/flow/thingspeak/thingspeak.c
- src/samples/flow/webservices/thingspeak-channel-update.fbp
Some warnings were raised when closing thingspeak nodes,
since finished connections
never were removed from pending vector.
> modules/thingspeak: fix connections management

- src/lib/io/sol-i2c-impl-linux.c
Soletta should match the Linux I2C name style. This will prevent
some problems that can occur when trying to use the I2C device via IIO.
> I2C: Use lowercase chars for I2C device numbers.

- src/lib/io/sol-i2c-impl-linux.c
The device address must have 4 characters. This was causing
some problems in IIO, because it was not possible to find the
correct path in the sysfs.
> I2C: Match the kernel's I2C address path.

- tools/build/Makefile.vars
It's broken since commit
d2bece2f9812 build: Respect the CC variable from the environment
Fix issue #2136
@bottazzini ptal
> build: fix HOSTCC issue

- tools/build/Makefile.targets
- tools/build/Makefile.vars
Make sure it won't consider make doxygen is done
when it fails (it has warnings).
For that create a success file when everything is
checked.
Fix #2258
> build: improve make doxygen rule

- src/lib/comms/sol-lwm2m-client.c
Changes from v1 (#2281):
- Added error returning.
This patch fixes a bug when a given LWM2M Server who owns a given
Access Control Object Instance tries to modify it (for instance,
to add or remove an ACL for a given third-party LWM2M Server).
There was no way to modify an Access Control Object Instance, since
the check_authorization() would fail, not finding an Access Control
Object Instance related to the target instance - which should not
exist anyway. To fix it, a new condition was added in case the target
'obj_id' == 'ACCESS_CONTROL_OBJECT_ID', in which we should only look
for the target 'instance_id' itself and then inside the OWNER Resource,
not looking for ACLs or anything else.
Signed-off-by: Bruno Melo <bsilva.melo@gmail.com>
> LWM2M: Fix check_authorization() for Access Control Objects [v2]

- src/lib/comms/sol-lwm2m-client.c
Otherwise sol_lwm2m_resource_clear() may be called on an uninitialized variable.
> lwm2m-client: Init the res variable.

- src/lib/comms/sol-lwm2m-client.c
- src/lib/comms/sol-lwm2m-common.c
- src/test/test-lwm2m.c
Changes from v1 (#2291):
- `enum` for states inside `observe_res_cb()`
- Chain of operations for the negative/corner-cases
- Docs describing all operations being performed and their outcome
This patch adds lwm2m tests covering all new functionality
added during GSoC, including: Bootstrap Interface, Access
Control Objects and CoAP Encryption (DTLS Security Modes).
Signed-off-by: Bruno Melo bsilva.melo@gmail.com
> LWM2M: Tests covering new functionality from GSoC [v2]

- data/scripts/libsoletta.sym
- src/lib/comms/include/sol-coap.h
- src/lib/comms/include/sol-lwm2m-bs-server.h
- src/lib/comms/include/sol-lwm2m-server.h
- src/lib/comms/include/sol-lwm2m.h
- src/lib/comms/include/sol-socket.h
- src/lib/comms/sol-coap.c
- src/lib/comms/sol-lwm2m-bs-server.c
- src/lib/comms/sol-lwm2m-client.c
- src/lib/comms/sol-lwm2m-common.c
- src/lib/comms/sol-lwm2m-common.h
- src/lib/comms/sol-lwm2m-security.c
- src/lib/comms/sol-lwm2m-security.h
- src/lib/comms/sol-lwm2m-server.c
- src/lib/comms/sol-socket-dtls-impl-tinydtls.c
- src/lib/comms/sol-socket-dtls.h
- src/samples/coap/lwm2m-bs-server.c
- src/samples/coap/lwm2m-client.c
- src/samples/coap/lwm2m-server.c
- src/test/test-lwm2m.c
Main changes since v2 (#2298)
- Minor memory leaking fixes
- Removed the "Ugly" patch for CoAP timeout. The timeout issue (which generates duplicated packets) seems to happen only in Client-Server/BSServer communication between the samples, and not in the same communication when it's done inside the `test-lwm2m.c` program. I guess it has something to do with the fact that the samples are running in different processes (since that's the only difference between samples and tests), but I still don't know what/where exactly is the issue.
Signed-off-by: Bruno Melo bsilva.melo@gmail.com
> LWM2M: Support for DTLS with Raw Public Key security mode [v3]

- src/lib/comms/sol-lwm2m-bs-server.c
- src/lib/comms/sol-lwm2m-common.h
This patch changes the type of the known_clients frield from
struct sol_lwm2m_bootstrap_server, to avoid possible issues in
case the user of the API deallocates the strings with the clients'
names.
Changes from v1 (#2302):
`bs_server->known_clients` as a `sol_ptr_vector` of `char *` instead of a `sol_vector` of `sol_str_slice`.
Signed-off-by: Bruno Melo <bsilva.melo@gmail.com>
> LWM2M: Change type of bs_server->known_clients [v2]

- data/scripts/libsoletta.sym
Add sol_netctl_service_get_security to libsoletta.sym.
Issue identified by check-api.
Signed-off-by: Anselmo L. S. Melo <anselmo.melo@intel.com>
> build: Add missing symbol to libsoletta.sym

- src/lib/io/include/sol-iio.h
- src/lib/io/sol-iio.c
- src/modules/flow/iio/iio.json
- src/modules/flow/iio/nodes.c
Signed-off-by: Gu Chaojie <chao.jie.gu@intel.com>
> IIO: Support oversampling_ratio configuration in IIO node

- src/samples/flow/js/Makefile
- tools/build/Makefile.rules
- tools/build/Makefile.targets
- tools/build/Makefile.vars
A few build issues were brought to my attention by @glima.
1. a parallel breakage with check-fbp-bin;
2. a parallel breakage with samples;
And I got a bonus fix with the gen-alias target - now converted to an actual rule and properly set into dep chain.
Regards....
> Random bs fixes
